import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import {UserProvider} from "./component/UserProvider";
import NavBar from "./component/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="bg-gray-300">
        <UserProvider>
            <NavBar />
            {children}
        </UserProvider>
        </body>
        </html>
    );
}
